### ISSUE TITLE
Add function to remove a target

### ISSUE THREAD

**Issue by jayfield1979** [squarefeet/THREE.TargetCamera#2]
Do you think it might be possible to have a function that removes a target (by name) from the target camera's target list?

This would be useful for something like tracking an object that get's destroyed like a bomb or, when an object gets re-parented.

**Comment by squarefeet** [comment]
Oh yeah, good call. Lemme see!

**Comment by squarefeet** [comment]
Righty-o, should be simple enough. A few questions though:
- When removing a target that's the current target, what target should the camera jump to? The first? Last? 
- Or do you want to be able to specify a replacement target? i.e. `camera.removeTarget( 'myBomb', 'enemy' )`, where arguments are`[ targetToRemove, targetToFocusOn ]`

**Comment by jayfield1979** [comment]
I could think of situations where both could be useful. Maybe have it so that if you call "removeTarget" and you don't pass an optional second argument, it jumps to the first, last or next in the targets list.

Of if the optional second argument is present, then it jumps to that target.

That would be awesome if possible and really makes your camera script very robust 

Cheers

**Comment by squarefeet** [comment]
Coolio. It's a pretty simple feature to implement, so give us a few minutes!

**Comment by jayfield1979** [comment]
You're a star. I'm working on something that's going to be projected on a large wall in the Southbank Centre, London that shows people interacting with a 3D scene via Twitter. Your camera script has made things easier and freed up my time to get the other stuff working. I'll give you a mention where appropriate.

I'll also show if you're interested.

James

**Comment by squarefeet** [comment]
Oh awesome, that sounds really interesting - I'll have to pop down there when it's running and have a gander! When's it going to be up?

**Comment by jayfield1979** [comment]
Yeah do it... It's a public event on from 29th - 31st May. It's part of the 'web we want' festival.

**Comment by squarefeet** [comment]
Sweet. I should be able to make it down on the 31st :)

**Comment by squarefeet** [comment]
Okie dokie, just pushed that to master so you should be able to play around with it. Let me know if you see any issues!

**Comment by jayfield1979** [comment]
Cheers. Enjoying some sun right now so will give it a go when the clouds rock up or it gets too cold!

**Comment by jayfield1979** [comment]
Tested both uses. Works perfectly. Thanks very much :)
