### ISSUE TITLE
Wow.  Just wow.

### ISSUE THREAD

**Issue by stickyfingies** [squarefeet/THREE.TargetCamera#4]
Hi squarefeet!  I know this isn't really categorized as an issue, sorry about that; but this is amazing.  I've been looking for a good game camera for three.js for a long time, and finally I found one - and  it's amazing! 💯 👍 Thanks again for making this!
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 🔢 💯

**Comment by squarefeet** [comment]
Ah, that's always nice to hear! Thank you, @cellman1234, glad you found a use for it :)
